name: Staging Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        php -r "unlink('composer-setup.php');"
        composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate Laravel application key
      run: php artisan key:generate

    - name: Run database migrations and seed
      run: php artisan migrate --seed --force

    - name: Deploy to Staging Server
      run: |
        rsync -avz --delete ./ user@staging.example.com:/path/to/your/app
      env:
        SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.STAGING_SSH_KNOWN_HOSTS }}

